"""One-shot 3.6.0 model-profile migration (R5 commit 2).

Override-key application stays in the frozen mapping and is executed later.
This step only backups deployment files and rewrites ``model_profiles.toml``.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from qq_ai_bot.deployment_setup.service import (
    SetupPaths,
    SetupValidationError,
    _atomic_write,
    _create_backup,
)
from qq_ai_bot.model_runtime.models import ModelTask
from qq_ai_bot.model_runtime.profiles import (
    MIGRATE_3_6_COMMAND,
    PROFILE_SCHEMA_VERSION,
    RETIRED_MODEL_ROUTES,
)

_ATTRIBUTION_FALLBACKS = ("utility_structured", "planner")
_MEMORY_FALLBACKS = (
    ("memory_self_reflection", "memory_extraction"),
    ("memory_consolidation", "memory_extraction"),
    ("memory_dream", "memory_consolidation"),
)


@dataclass(frozen=True, slots=True)
class ModelProfileMigrationResult:
    changed: bool
    backup: Path | None
    materialized_attribution_from: str | None
    removed_routes: tuple[str, ...]


def migrate_deployment_model_profiles(paths: SetupPaths) -> ModelProfileMigrationResult:
    """Backup deployment files and rewrite schema v2 profiles to v3."""

    existing = tuple(
        path for path in (paths.env, paths.model_profiles, paths.mcp) if path.is_file()
    )
    if not paths.model_profiles.is_file():
        return ModelProfileMigrationResult(
            changed=False,
            backup=_create_backup(paths, existing),
            materialized_attribution_from=None,
            removed_routes=(),
        )
    try:
        original = paths.model_profiles.read_text(encoding="utf-8")
        document = tomllib.loads(original)
    except (OSError, UnicodeError, tomllib.TOMLDecodeError) as exc:
        raise SetupValidationError(f"无法读取 config/model_profiles.toml: {exc}") from exc
    migrated, attribution_source, removed = _migrate_profile_document(document)
    rendered = _emit_profile_document(migrated)
    changed = rendered != original
    backup = _create_backup(paths, existing)
    if changed:
        _atomic_write(paths.model_profiles, rendered.encode("utf-8"), private=False)
    return ModelProfileMigrationResult(
        changed=changed,
        backup=backup,
        materialized_attribution_from=attribution_source,
        removed_routes=removed,
    )


def _migrate_profile_document(
    document: dict[str, Any],
) -> tuple[dict[str, Any], str | None, tuple[str, ...]]:
    profiles = document.get("profiles")
    routes = document.get("routes")
    if not isinstance(profiles, dict) or not isinstance(routes, dict):
        raise SetupValidationError("model_profiles.toml 缺少 profiles 或 routes")
    next_routes = {str(key): str(value) for key, value in routes.items()}
    attribution_source: str | None = None
    if "memory_attribution" not in next_routes:
        for source in _ATTRIBUTION_FALLBACKS:
            if source in next_routes:
                next_routes["memory_attribution"] = next_routes[source]
                attribution_source = source
                break
    for target, source in _MEMORY_FALLBACKS:
        if target not in next_routes and source in next_routes:
            next_routes[target] = next_routes[source]
    fill_from = next_routes.get("chat_agent") or next_routes.get("planner")
    if fill_from is not None:
        for task in ModelTask:
            next_routes.setdefault(task.value, fill_from)
    removed = tuple(sorted(name for name in RETIRED_MODEL_ROUTES if name in next_routes))
    for name in removed:
        del next_routes[name]
    missing = [task.value for task in ModelTask if task.value not in next_routes]
    if missing:
        raise SetupValidationError(
            "migrate-3-6 无法补齐模型路由："
            + ", ".join(missing)
            + f"；请先补齐 routes 或运行 Guided Setup。命令：{MIGRATE_3_6_COMMAND}"
        )
    return (
        {
            "schema_version": PROFILE_SCHEMA_VERSION,
            "profiles": profiles,
            "routes": next_routes,
        },
        attribution_source,
        removed,
    )


def _emit_profile_document(document: dict[str, Any]) -> str:
    lines = [
        f"schema_version = {int(document['schema_version'])}",
        "",
        "# Generated by qq-ai-bot-cli setup migrate-3-6. Secrets remain in .env.",
    ]
    profiles = document["profiles"]
    if not isinstance(profiles, dict):
        raise SetupValidationError("model_profiles.toml profiles 必须是表")
    for profile_id, payload in profiles.items():
        if not isinstance(payload, dict):
            raise SetupValidationError(f"profile {profile_id} 必须是表")
        lines.append("")
        lines.append(f"[profiles.{profile_id}]")
        for key, value in payload.items():
            lines.append(f"{key} = {_toml_value(value)}")
    lines.extend(("", "[routes]"))
    routes = document["routes"]
    if not isinstance(routes, dict):
        raise SetupValidationError("model_profiles.toml routes 必须是表")
    for task in ModelTask:
        lines.append(f'{task.value} = "{routes[task.value]}"')
    return "\n".join(lines) + "\n"


def _toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        return repr(value) if value != int(value) else f"{value:.1f}"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    raise SetupValidationError(f"无法序列化 model profile 字段: {type(value).__name__}")
