"""Conversation Runtime and Plugin API 2.0 runtime configuration declarations."""

from __future__ import annotations

from qq_ai_bot.admin.config_spec_helpers import _G, _GG, _GGU, _field, _spec
from qq_ai_bot.admin.models import ConfigApplyMode, ConfigSpec


def planner_plugin_config_specs() -> tuple[ConfigSpec, ...]:
    """Return reviewed conversation, reply-sequence, and plugin host settings."""

    return (
        _spec(
            "reply.cancel_on_new_message",
            "新消息停止剩余分句",
            "新消息到达后是否停止旧轮次尚未发送的消息。",
            value_type="boolean",
            scopes=_GGU,
            env_alias="REPLY_SEQUENCE_CANCEL_ON_NEW_MESSAGE",
            getter=_field("reply_sequence_cancel_on_new_message"),
            settings_fields=("reply_sequence_cancel_on_new_message",),
            category="reply",
        ),
        _spec(
            "reply.hard_max_messages",
            "回复消息硬上限",
            "单轮实际发送 QQ 消息数的绝对上限。",
            aliases=("单轮发送硬上限", "单轮消息上限"),
            value_type="integer",
            minimum=1,
            maximum=20,
            scopes=_GGU,
            env_alias="REPLY_HARD_MAX_MESSAGES",
            getter=_field("reply_hard_max_messages"),
            settings_fields=("reply_hard_max_messages",),
            category="reply",
        ),
        _spec(
            "conversation.autonomous_enabled",
            "群聊自主参与",
            "未 @ / 未回复时是否允许本地评分后进入 Main Agent。",
            value_type="boolean",
            scopes=_GG,
            env_alias="CONVERSATION_AUTONOMOUS_ENABLED",
            getter=_field("conversation_autonomous_enabled"),
            settings_fields=("conversation_autonomous_enabled",),
            category="conversation",
        ),
        _spec(
            "conversation.autonomous_debounce_seconds",
            "群聊自主去抖",
            "聚合连续群消息后再评分的等待秒数。",
            value_type="number",
            minimum=0,
            maximum=60,
            scopes=_GG,
            env_alias="CONVERSATION_AUTONOMOUS_DEBOUNCE_SECONDS",
            getter=_field("conversation_autonomous_debounce_seconds"),
            settings_fields=("conversation_autonomous_debounce_seconds",),
            category="conversation",
        ),
        _spec(
            "conversation.autonomous_admission_threshold",
            "自主参与评分阈值",
            "未触发群消息进入 Main Agent 的本地评分阈值。",
            value_type="integer",
            minimum=0,
            maximum=100,
            scopes=_GG,
            env_alias="CONVERSATION_AUTONOMOUS_ADMISSION_THRESHOLD",
            getter=_field("conversation_autonomous_admission_threshold"),
            settings_fields=("conversation_autonomous_admission_threshold",),
            category="conversation",
        ),
        _spec(
            "conversation.autonomous_batch_limit",
            "自主批次消息数",
            "一次自主评分最多观察的近期人类消息数量。",
            aliases=("max pending messages", "自主批次上限", "批次消息数"),
            value_type="integer",
            minimum=1,
            maximum=100,
            scopes=_GG,
            env_alias="CONVERSATION_AUTONOMOUS_BATCH_LIMIT",
            getter=_field("conversation_autonomous_batch_limit"),
            settings_fields=("conversation_autonomous_batch_limit",),
            category="conversation",
        ),
        _spec(
            "conversation.autonomous_presence_window_seconds",
            "自主存在感窗口",
            "计算近期自身发言占比的窗口秒数。",
            value_type="integer",
            minimum=1,
            maximum=86400,
            scopes=_GG,
            env_alias="CONVERSATION_AUTONOMOUS_PRESENCE_WINDOW_SECONDS",
            getter=_field("conversation_autonomous_presence_window_seconds"),
            settings_fields=("conversation_autonomous_presence_window_seconds",),
            category="conversation",
        ),
        _spec(
            "conversation.interrupt_autonomous_on_new_message",
            "新消息中断自主轮次",
            "群内新消息是否中断旧的自主轮次和未发送回复。",
            value_type="boolean",
            scopes=_GG,
            env_alias="CONVERSATION_INTERRUPT_AUTONOMOUS_ON_NEW_MESSAGE",
            getter=_field("conversation_interrupt_autonomous_on_new_message"),
            settings_fields=("conversation_interrupt_autonomous_on_new_message",),
            category="conversation",
        ),
        _spec(
            "plugins.hook_timeout_seconds",
            "插件 Hook 超时",
            "单个插件事件 Hook 的最长执行秒数。",
            value_type="number",
            minimum=0.1,
            maximum=60,
            scopes=_G,
            env_alias="PLUGIN_HOOK_TIMEOUT_SECONDS",
            getter=_field("plugin_hook_timeout_seconds"),
            settings_fields=("plugin_hook_timeout_seconds",),
            category="plugins",
        ),
        _spec(
            "plugins.max_prompt_fragment_characters",
            "插件 Prompt 单片段预算",
            "单个插件 Prompt Fragment 的字符上限。",
            value_type="integer",
            minimum=1,
            maximum=20000,
            scopes=_G,
            env_alias="PLUGIN_MAX_PROMPT_FRAGMENT_CHARACTERS",
            getter=_field("plugin_max_prompt_fragment_characters"),
            settings_fields=("plugin_max_prompt_fragment_characters",),
            category="plugins",
        ),
        _spec(
            "plugins.max_prompt_characters_per_plugin",
            "单插件 Prompt 预算",
            "单个插件贡献的所有 Prompt 字符上限。",
            value_type="integer",
            minimum=1,
            maximum=40000,
            scopes=_G,
            env_alias="PLUGIN_MAX_PROMPT_CHARACTERS_PER_PLUGIN",
            getter=_field("plugin_max_prompt_characters_per_plugin"),
            settings_fields=("plugin_max_prompt_characters_per_plugin",),
            category="plugins",
        ),
        _spec(
            "plugins.max_total_prompt_characters",
            "插件 Prompt 总预算",
            "一轮所有插件 Prompt 的总字符上限。",
            value_type="integer",
            minimum=2,
            maximum=100000,
            scopes=_G,
            env_alias="PLUGIN_MAX_TOTAL_PROMPT_CHARACTERS",
            getter=_field("plugin_max_total_prompt_characters"),
            settings_fields=("plugin_max_total_prompt_characters",),
            category="plugins",
        ),
        _spec(
            "plugins.enabled",
            "外部插件系统",
            "重启后是否发现和启动已批准的本地插件。",
            value_type="boolean",
            scopes=_G,
            mode=ConfigApplyMode.RESTART_REQUIRED,
            env_alias="PLUGIN_SYSTEM_ENABLED",
            getter=_field("plugin_system_enabled"),
            settings_fields=("plugin_system_enabled",),
            category="plugins",
        ),
        _spec(
            "plugins.directory",
            "插件目录",
            "重启后扫描的本地可信插件目录。",
            value_type="string",
            scopes=_G,
            mode=ConfigApplyMode.RESTART_REQUIRED,
            env_alias="PLUGIN_DIRECTORY",
            getter=lambda settings: str(settings.plugin_directory),
            settings_fields=("plugin_directory",),
            category="plugins",
        ),
        _spec(
            "plugins.api_version",
            "Plugin API 版本",
            "重启后 Host 接受的 Plugin API major.minor 版本。",
            value_type="string",
            scopes=_G,
            mode=ConfigApplyMode.RESTART_REQUIRED,
            env_alias="PLUGIN_API_VERSION",
            getter=_field("plugin_api_version"),
            settings_fields=("plugin_api_version",),
            category="plugins",
        ),
    )
